<?php
// @formatter:off

namespace PHPSTORM_META {

   /**
    * PhpStorm Meta file, to provide autocomplete information for PhpStorm
    * Generated on 2018-09-11 22:00:51.
    *
    * @author Barry vd. Heuvel <barryvdh@gmail.com>
    * @see https://github.com/barryvdh/laravel-ide-helper
    */
    override(new \Illuminate\Contracts\Container\Container, map([
        '' => '@',
        'App\Porter' => \App\Porter::class,
        'App\Support\Console\ConsoleWriter' => \App\Support\Console\ConsoleWriter::class,
        'App\Support\Console\ServerBag' => \App\Support\Console\ServerBag::class,
        'App\Support\Contracts\Cli' => \App\Support\Console\Cli::class,
        'App\Support\Contracts\ImageSetRepository' => \App\Support\Images\ImageSetRepository::class,
        'App\Support\Ssl\CertificateBuilder' => \App\Support\Ssl\CertificateBuilder::class,
        'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
        'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
        'Illuminate\Contracts\Debug\ExceptionHandler' => \Illuminate\Foundation\Exceptions\Handler::class,
        'Illuminate\Contracts\Queue\EntityResolver' => \Illuminate\Database\Eloquent\QueueEntityResolver::class,
        'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
        'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
        'cache' => \Illuminate\Cache\CacheManager::class,
        'cache.store' => \Illuminate\Cache\Repository::class,
        'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
        'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
        'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
        'command.tinker' => \Intonate\TinkerZero\Console\TinkerZeroCommand::class,
        'composer' => \LaravelZero\Framework\Providers\Composer\Composer::class,
        'db' => \Illuminate\Database\DatabaseManager::class,
        'db.connection' => \Illuminate\Database\SQLiteConnection::class,
        'db.factory' => \Illuminate\Database\Connectors\ConnectionFactory::class,
        'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
        'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
        'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
        'migration.creator' => \Illuminate\Database\Migrations\MigrationCreator::class,
        'migration.repository' => \Illuminate\Database\Migrations\DatabaseMigrationRepository::class,
        'migrator' => \LaravelZero\Framework\Components\Database\Migrator::class,
        'view' => \Illuminate\View\Factory::class,
        'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
        'view.finder' => \Illuminate\View\FileViewFinder::class,
    ]));
    override(\Illuminate\Contracts\Container\Container::make(0), map([
        '' => '@',
        'App\Porter' => \App\Porter::class,
        'App\Support\Console\ConsoleWriter' => \App\Support\Console\ConsoleWriter::class,
        'App\Support\Console\ServerBag' => \App\Support\Console\ServerBag::class,
        'App\Support\Contracts\Cli' => \App\Support\Console\Cli::class,
        'App\Support\Contracts\ImageSetRepository' => \App\Support\Images\ImageSetRepository::class,
        'App\Support\Ssl\CertificateBuilder' => \App\Support\Ssl\CertificateBuilder::class,
        'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
        'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
        'Illuminate\Contracts\Debug\ExceptionHandler' => \Illuminate\Foundation\Exceptions\Handler::class,
        'Illuminate\Contracts\Queue\EntityResolver' => \Illuminate\Database\Eloquent\QueueEntityResolver::class,
        'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
        'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
        'cache' => \Illuminate\Cache\CacheManager::class,
        'cache.store' => \Illuminate\Cache\Repository::class,
        'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
        'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
        'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
        'command.tinker' => \Intonate\TinkerZero\Console\TinkerZeroCommand::class,
        'composer' => \LaravelZero\Framework\Providers\Composer\Composer::class,
        'db' => \Illuminate\Database\DatabaseManager::class,
        'db.connection' => \Illuminate\Database\SQLiteConnection::class,
        'db.factory' => \Illuminate\Database\Connectors\ConnectionFactory::class,
        'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
        'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
        'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
        'migration.creator' => \Illuminate\Database\Migrations\MigrationCreator::class,
        'migration.repository' => \Illuminate\Database\Migrations\DatabaseMigrationRepository::class,
        'migrator' => \LaravelZero\Framework\Components\Database\Migrator::class,
        'view' => \Illuminate\View\Factory::class,
        'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
        'view.finder' => \Illuminate\View\FileViewFinder::class,
    ]));
    override(\Illuminate\Contracts\Container\Container::makeWith(0), map([
        '' => '@',
        'App\Porter' => \App\Porter::class,
        'App\Support\Console\ConsoleWriter' => \App\Support\Console\ConsoleWriter::class,
        'App\Support\Console\ServerBag' => \App\Support\Console\ServerBag::class,
        'App\Support\Contracts\Cli' => \App\Support\Console\Cli::class,
        'App\Support\Contracts\ImageSetRepository' => \App\Support\Images\ImageSetRepository::class,
        'App\Support\Ssl\CertificateBuilder' => \App\Support\Ssl\CertificateBuilder::class,
        'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
        'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
        'Illuminate\Contracts\Debug\ExceptionHandler' => \Illuminate\Foundation\Exceptions\Handler::class,
        'Illuminate\Contracts\Queue\EntityResolver' => \Illuminate\Database\Eloquent\QueueEntityResolver::class,
        'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
        'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
        'cache' => \Illuminate\Cache\CacheManager::class,
        'cache.store' => \Illuminate\Cache\Repository::class,
        'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
        'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
        'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
        'command.tinker' => \Intonate\TinkerZero\Console\TinkerZeroCommand::class,
        'composer' => \LaravelZero\Framework\Providers\Composer\Composer::class,
        'db' => \Illuminate\Database\DatabaseManager::class,
        'db.connection' => \Illuminate\Database\SQLiteConnection::class,
        'db.factory' => \Illuminate\Database\Connectors\ConnectionFactory::class,
        'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
        'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
        'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
        'migration.creator' => \Illuminate\Database\Migrations\MigrationCreator::class,
        'migration.repository' => \Illuminate\Database\Migrations\DatabaseMigrationRepository::class,
        'migrator' => \LaravelZero\Framework\Components\Database\Migrator::class,
        'view' => \Illuminate\View\Factory::class,
        'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
        'view.finder' => \Illuminate\View\FileViewFinder::class,
    ]));
    override(\App::make(0), map([
        '' => '@',
        'App\Porter' => \App\Porter::class,
        'App\Support\Console\ConsoleWriter' => \App\Support\Console\ConsoleWriter::class,
        'App\Support\Console\ServerBag' => \App\Support\Console\ServerBag::class,
        'App\Support\Contracts\Cli' => \App\Support\Console\Cli::class,
        'App\Support\Contracts\ImageSetRepository' => \App\Support\Images\ImageSetRepository::class,
        'App\Support\Ssl\CertificateBuilder' => \App\Support\Ssl\CertificateBuilder::class,
        'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
        'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
        'Illuminate\Contracts\Debug\ExceptionHandler' => \Illuminate\Foundation\Exceptions\Handler::class,
        'Illuminate\Contracts\Queue\EntityResolver' => \Illuminate\Database\Eloquent\QueueEntityResolver::class,
        'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
        'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
        'cache' => \Illuminate\Cache\CacheManager::class,
        'cache.store' => \Illuminate\Cache\Repository::class,
        'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
        'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
        'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
        'command.tinker' => \Intonate\TinkerZero\Console\TinkerZeroCommand::class,
        'composer' => \LaravelZero\Framework\Providers\Composer\Composer::class,
        'db' => \Illuminate\Database\DatabaseManager::class,
        'db.connection' => \Illuminate\Database\SQLiteConnection::class,
        'db.factory' => \Illuminate\Database\Connectors\ConnectionFactory::class,
        'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
        'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
        'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
        'migration.creator' => \Illuminate\Database\Migrations\MigrationCreator::class,
        'migration.repository' => \Illuminate\Database\Migrations\DatabaseMigrationRepository::class,
        'migrator' => \LaravelZero\Framework\Components\Database\Migrator::class,
        'view' => \Illuminate\View\Factory::class,
        'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
        'view.finder' => \Illuminate\View\FileViewFinder::class,
    ]));
    override(\App::makeWith(0), map([
        '' => '@',
        'App\Porter' => \App\Porter::class,
        'App\Support\Console\ConsoleWriter' => \App\Support\Console\ConsoleWriter::class,
        'App\Support\Console\ServerBag' => \App\Support\Console\ServerBag::class,
        'App\Support\Contracts\Cli' => \App\Support\Console\Cli::class,
        'App\Support\Contracts\ImageSetRepository' => \App\Support\Images\ImageSetRepository::class,
        'App\Support\Ssl\CertificateBuilder' => \App\Support\Ssl\CertificateBuilder::class,
        'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
        'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
        'Illuminate\Contracts\Debug\ExceptionHandler' => \Illuminate\Foundation\Exceptions\Handler::class,
        'Illuminate\Contracts\Queue\EntityResolver' => \Illuminate\Database\Eloquent\QueueEntityResolver::class,
        'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
        'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
        'cache' => \Illuminate\Cache\CacheManager::class,
        'cache.store' => \Illuminate\Cache\Repository::class,
        'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
        'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
        'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
        'command.tinker' => \Intonate\TinkerZero\Console\TinkerZeroCommand::class,
        'composer' => \LaravelZero\Framework\Providers\Composer\Composer::class,
        'db' => \Illuminate\Database\DatabaseManager::class,
        'db.connection' => \Illuminate\Database\SQLiteConnection::class,
        'db.factory' => \Illuminate\Database\Connectors\ConnectionFactory::class,
        'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
        'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
        'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
        'migration.creator' => \Illuminate\Database\Migrations\MigrationCreator::class,
        'migration.repository' => \Illuminate\Database\Migrations\DatabaseMigrationRepository::class,
        'migrator' => \LaravelZero\Framework\Components\Database\Migrator::class,
        'view' => \Illuminate\View\Factory::class,
        'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
        'view.finder' => \Illuminate\View\FileViewFinder::class,
    ]));
    override(\app(0), map([
        '' => '@',
        'App\Porter' => \App\Porter::class,
        'App\Support\Console\ConsoleWriter' => \App\Support\Console\ConsoleWriter::class,
        'App\Support\Console\ServerBag' => \App\Support\Console\ServerBag::class,
        'App\Support\Contracts\Cli' => \App\Support\Console\Cli::class,
        'App\Support\Contracts\ImageSetRepository' => \App\Support\Images\ImageSetRepository::class,
        'App\Support\Ssl\CertificateBuilder' => \App\Support\Ssl\CertificateBuilder::class,
        'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
        'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
        'Illuminate\Contracts\Debug\ExceptionHandler' => \Illuminate\Foundation\Exceptions\Handler::class,
        'Illuminate\Contracts\Queue\EntityResolver' => \Illuminate\Database\Eloquent\QueueEntityResolver::class,
        'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
        'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
        'cache' => \Illuminate\Cache\CacheManager::class,
        'cache.store' => \Illuminate\Cache\Repository::class,
        'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
        'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
        'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
        'command.tinker' => \Intonate\TinkerZero\Console\TinkerZeroCommand::class,
        'composer' => \LaravelZero\Framework\Providers\Composer\Composer::class,
        'db' => \Illuminate\Database\DatabaseManager::class,
        'db.connection' => \Illuminate\Database\SQLiteConnection::class,
        'db.factory' => \Illuminate\Database\Connectors\ConnectionFactory::class,
        'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
        'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
        'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
        'migration.creator' => \Illuminate\Database\Migrations\MigrationCreator::class,
        'migration.repository' => \Illuminate\Database\Migrations\DatabaseMigrationRepository::class,
        'migrator' => \LaravelZero\Framework\Components\Database\Migrator::class,
        'view' => \Illuminate\View\Factory::class,
        'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
        'view.finder' => \Illuminate\View\FileViewFinder::class,
    ]));
    override(\resolve(0), map([
        '' => '@',
        'App\Porter' => \App\Porter::class,
        'App\Support\Console\ConsoleWriter' => \App\Support\Console\ConsoleWriter::class,
        'App\Support\Console\ServerBag' => \App\Support\Console\ServerBag::class,
        'App\Support\Contracts\Cli' => \App\Support\Console\Cli::class,
        'App\Support\Contracts\ImageSetRepository' => \App\Support\Images\ImageSetRepository::class,
        'App\Support\Ssl\CertificateBuilder' => \App\Support\Ssl\CertificateBuilder::class,
        'Illuminate\Console\Scheduling\Schedule' => \Illuminate\Console\Scheduling\Schedule::class,
        'Illuminate\Contracts\Console\Kernel' => \LaravelZero\Framework\Kernel::class,
        'Illuminate\Contracts\Debug\ExceptionHandler' => \Illuminate\Foundation\Exceptions\Handler::class,
        'Illuminate\Contracts\Queue\EntityResolver' => \Illuminate\Database\Eloquent\QueueEntityResolver::class,
        'NunoMaduro\LaravelConsoleSummary\Contracts\DescriberContract' => \NunoMaduro\LaravelConsoleSummary\Describer::class,
        'blade.compiler' => \Illuminate\View\Compilers\BladeCompiler::class,
        'cache' => \Illuminate\Cache\CacheManager::class,
        'cache.store' => \Illuminate\Cache\Repository::class,
        'command.ide-helper.eloquent' => \Barryvdh\LaravelIdeHelper\Console\EloquentCommand::class,
        'command.ide-helper.generate' => \Barryvdh\LaravelIdeHelper\Console\GeneratorCommand::class,
        'command.ide-helper.meta' => \Barryvdh\LaravelIdeHelper\Console\MetaCommand::class,
        'command.ide-helper.models' => \Barryvdh\LaravelIdeHelper\Console\ModelsCommand::class,
        'command.tinker' => \Intonate\TinkerZero\Console\TinkerZeroCommand::class,
        'composer' => \LaravelZero\Framework\Providers\Composer\Composer::class,
        'db' => \Illuminate\Database\DatabaseManager::class,
        'db.connection' => \Illuminate\Database\SQLiteConnection::class,
        'db.factory' => \Illuminate\Database\Connectors\ConnectionFactory::class,
        'desktop.notification' => \NunoMaduro\LaravelDesktopNotifier\Notification::class,
        'desktop.notifier' => \NunoMaduro\LaravelDesktopNotifier\Notifier::class,
        'events' => \Illuminate\Events\Dispatcher::class,
        'files' => \Illuminate\Filesystem\Filesystem::class,
        'filesystem' => \Illuminate\Filesystem\FilesystemManager::class,
        'filesystem.cloud' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'filesystem.disk' => \Illuminate\Filesystem\FilesystemAdapter::class,
        'memcached.connector' => \Illuminate\Cache\MemcachedConnector::class,
        'migration.creator' => \Illuminate\Database\Migrations\MigrationCreator::class,
        'migration.repository' => \Illuminate\Database\Migrations\DatabaseMigrationRepository::class,
        'migrator' => \LaravelZero\Framework\Components\Database\Migrator::class,
        'view' => \Illuminate\View\Factory::class,
        'view.engine.resolver' => \Illuminate\View\Engines\EngineResolver::class,
        'view.finder' => \Illuminate\View\FileViewFinder::class,
    ]));

    override(\Illuminate\Support\Arr::add(0), type(0));
    override(\Illuminate\Support\Arr::except(0), type(0));
    override(\Illuminate\Support\Arr::first(0), elementType(0));
    override(\Illuminate\Support\Arr::last(0), elementType(0));
    override(\Illuminate\Support\Arr::get(0), elementType(0));
    override(\Illuminate\Support\Arr::only(0), type(0));
    override(\Illuminate\Support\Arr::prepend(0), type(0));
    override(\Illuminate\Support\Arr::pull(0), elementType(0));
    override(\Illuminate\Support\Arr::set(0), type(0));
    override(\Illuminate\Support\Arr::shuffle(0), type(0));
    override(\Illuminate\Support\Arr::sort(0), type(0));
    override(\Illuminate\Support\Arr::sortRecursive(0), type(0));
    override(\Illuminate\Support\Arr::where(0), type(0));
    override(\array_add(0), type(0));
    override(\array_except(0), type(0));
    override(\array_first(0), elementType(0));
    override(\array_last(0), elementType(0));
    override(\array_get(0), elementType(0));
    override(\array_only(0), type(0));
    override(\array_prepend(0), type(0));
    override(\array_pull(0), elementType(0));
    override(\array_set(0), type(0));
    override(\array_sort(0), type(0));
    override(\array_sort_recursive(0), type(0));
    override(\array_where(0), type(0));
    override(\head(0), elementType(0));
    override(\last(0), elementType(0));
    override(\with(0), type(0));
    override(\tap(0), type(0));

}
